version: '3.8'

services:
  postgres:
    image: ankane/pgvector:v0.5.1
    container_name: rove_pgvector
    restart: always
    environment:
      POSTGRES_DB: rove_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres_password
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
